<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-29 19:56
=======
# Generated by Django 5.1.7 on 2025-04-29 19:07
>>>>>>> d6960a7c8cab442c4375c55f54934bc3378a57e3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.CharField(max_length=255)),
                ("is_for_rent", models.BooleanField(default=False)),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> d6960a7c8cab442c4375c55f54934bc3378a57e3
            ],
        ),
    ]
